<?php
return array(
    'router' => array(
        'routes' => array(
            'inventory.rest.barang' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/barang[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\Barang\\Controller',
                    ),
                ),
            ),
            'inventory.rest.kategori' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/kategori[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\Kategori\\Controller',
                    ),
                ),
            ),
            'inventory.rest.satuan' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/satuan[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\Satuan\\Controller',
                    ),
                ),
            ),
            'inventory.rest.penyedia' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/penyedia[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\Penyedia\\Controller',
                    ),
                ),
            ),
            'inventory.rest.barang-ruangan' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/barangruangan[/:ruangan]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\BarangRuangan\\Controller',
                    ),
                ),
            ),
            'inventory.rest.penerimaan' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/penerimaan[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\Penerimaan\\Controller',
                    ),
                ),
            ),
            'inventory.rest.permintaan' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/permintaan[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\Permintaan\\Controller',
                    ),
                ),
            ),
            'inventory.rest.permintaan-detil' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/permintaandetil[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PermintaanDetil\\Controller',
                    ),
                ),
            ),
            'inventory.rest.pengiriman' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/pengiriman[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\Pengiriman\\Controller',
                    ),
                ),
            ),
            'inventory.rest.pengiriman-detil' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/pengirimandetil[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PengirimanDetil\\Controller',
                    ),
                ),
            ),
            'inventory.rest.harga-barang' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/hargabarang[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\HargaBarang\\Controller',
                    ),
                ),
            ),
            'inventory.rest.stok-opname' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/stokopname[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\StokOpname\\Controller',
                    ),
                ),
            ),
            'inventory.rest.stok-opname-detil' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/stokopnamedetil[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller',
                    ),
                ),
            ),
            'inventory.rest.transaksi-stok-ruangan' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/transaksistokruangan[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller',
                    ),
                ),
            ),
            'inventory.rest.penerimaan-barang' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/penerimaanbarang[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller',
                    ),
                ),
            ),
            'inventory.rest.penerimaan-barang-detil' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/penerimaanbarangdetil[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller',
                    ),
                ),
            ),
            'inventory.rest.pengembalian-barang' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/pengembalianbarang[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PengembalianBarang\\Controller',
                    ),
                ),
            ),
            'inventory.rest.pengembalian-barang-detil' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/pengembalianbarangdetil[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller',
                    ),
                ),
            ),
            'inventory.rest.pembatalan-penerimaan-barang' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/pembatalanpenerimaanbarang[/:pembatalan_penerimaan_barang_id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller',
                    ),
                ),
            ),
            'inventory.rest.stok-barang-minimum' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/stokbarangminimum[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller',
                    ),
                ),
            ),
            'inventory.rest.paket-farmasi' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/inventory/paketfarmasi[/:id]',
                    'defaults' => array(
                        'controller' => 'Inventory\\V1\\Rest\\PaketFarmasi\\Controller',
                    ),
                ),
            ),
        ),
    ),
    'zf-versioning' => array(
        'uri' => array(
            0 => 'inventory.rest.barang',
            1 => 'inventory.rest.kategori',
            2 => 'inventory.rest.satuan',
            3 => 'inventory.rest.penyedia',
            4 => 'inventory.rest.barang-ruangan',
            6 => 'inventory.rest.penerimaan',
            7 => 'inventory.rest.permintaan',
            8 => 'inventory.rest.permintaan-detil',
            9 => 'inventory.rest.pengiriman',
            10 => 'inventory.rest.pengiriman-detil',
            11 => 'inventory.rest.harga-barang',
            13 => 'inventory.rest.stok-opname',
            14 => 'inventory.rest.stok-opname',
            15 => 'inventory.rest.stok-opname-detil',
            16 => 'inventory.rest.transaksi-stok-ruangan',
            17 => 'inventory.rest.penerimaan-barang',
            18 => 'inventory.rest.penerimaan-barang-detil',
            19 => 'inventory.rest.pengembalian-barang',
            20 => 'inventory.rest.pengembalian-barang-detil',
            21 => 'inventory.rest.pembatalan-penerimaan-barang',
            31 => 'inventory.rest.stok-barang-minimum',
            32 => 'inventory.rest.paket-farmasi',
        ),
    ),
    'service_manager' => array(
        'factories' => array(
            'Inventory\\V1\\Rest\\Barang\\BarangResource' => 'Inventory\\V1\\Rest\\Barang\\BarangResourceFactory',
            'Inventory\\V1\\Rest\\Kategori\\KategoriResource' => 'Inventory\\V1\\Rest\\Kategori\\KategoriResourceFactory',
            'Inventory\\V1\\Rest\\Satuan\\SatuanResource' => 'Inventory\\V1\\Rest\\Satuan\\SatuanResourceFactory',
            'Inventory\\V1\\Rest\\Penyedia\\PenyediaResource' => 'Inventory\\V1\\Rest\\Penyedia\\PenyediaResourceFactory',
            'Inventory\\V1\\Rest\\BarangRuangan\\BarangRuanganResource' => 'Inventory\\V1\\Rest\\BarangRuangan\\BarangRuanganResourceFactory',
            'Inventory\\V1\\Rest\\Penerimaan\\PenerimaanResource' => 'Inventory\\V1\\Rest\\Penerimaan\\PenerimaanResourceFactory',
            'Inventory\\V1\\Rest\\Permintaan\\PermintaanResource' => 'Inventory\\V1\\Rest\\Permintaan\\PermintaanResourceFactory',
            'Inventory\\V1\\Rest\\PermintaanDetil\\PermintaanDetilResource' => 'Inventory\\V1\\Rest\\PermintaanDetil\\PermintaanDetilResourceFactory',
            'Inventory\\V1\\Rest\\Pengiriman\\PengirimanResource' => 'Inventory\\V1\\Rest\\Pengiriman\\PengirimanResourceFactory',
            'Inventory\\V1\\Rest\\PengirimanDetil\\PengirimanDetilResource' => 'Inventory\\V1\\Rest\\PengirimanDetil\\PengirimanDetilResourceFactory',
            'Inventory\\V1\\Rest\\HargaBarang\\HargaBarangResource' => 'Inventory\\V1\\Rest\\HargaBarang\\HargaBarangResourceFactory',
            'Inventory\\V1\\Rest\\StokOpname\\StokOpnameResource' => 'Inventory\\V1\\Rest\\StokOpname\\StokOpnameResourceFactory',
            'Inventory\\V1\\Rest\\StokOpnameDetil\\StokOpnameDetilResource' => 'Inventory\\V1\\Rest\\StokOpnameDetil\\StokOpnameDetilResourceFactory',
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\TransaksiStokRuanganResource' => 'Inventory\\V1\\Rest\\TransaksiStokRuangan\\TransaksiStokRuanganResourceFactory',
            'Inventory\\V1\\Rest\\PenerimaanBarang\\PenerimaanBarangResource' => 'Inventory\\V1\\Rest\\PenerimaanBarang\\PenerimaanBarangResourceFactory',
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\PenerimaanBarangDetilResource' => 'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\PenerimaanBarangDetilResourceFactory',
            'Inventory\\V1\\Rest\\PengembalianBarang\\PengembalianBarangResource' => 'Inventory\\V1\\Rest\\PengembalianBarang\\PengembalianBarangResourceFactory',
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\PengembalianBarangDetilResource' => 'Inventory\\V1\\Rest\\PengembalianBarangDetil\\PengembalianBarangDetilResourceFactory',
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\PembatalanPenerimaanBarangResource' => 'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\PembatalanPenerimaanBarangResourceFactory',
            'Inventory\\V1\\Rest\\StokBarangMinimum\\StokBarangMinimumResource' => 'Inventory\\V1\\Rest\\StokBarangMinimum\\StokBarangMinimumResourceFactory',
            'Inventory\\V1\\Rest\\PaketFarmasi\\PaketFarmasiResource' => 'Inventory\\V1\\Rest\\PaketFarmasi\\PaketFarmasiResourceFactory',
        ),
    ),
    'zf-rest' => array(
        'Inventory\\V1\\Rest\\Barang\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\Barang\\BarangResource',
            'route_name' => 'inventory.rest.barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'barang',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'ID',
                1 => 'NAMA',
                2 => 'KATEGORI',
                3 => 'QUERY',
                4 => 'start',
                5 => 'limit',
                6 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\Barang\\BarangEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\Barang\\BarangCollection',
            'service_name' => 'Barang',
        ),
        'Inventory\\V1\\Rest\\Kategori\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\Kategori\\KategoriResource',
            'route_name' => 'inventory.rest.kategori',
            'route_identifier_name' => 'id',
            'collection_name' => 'kategori',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'ID',
                1 => 'NAMA',
                2 => 'JENIS',
                3 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\Kategori\\KategoriEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\Kategori\\KategoriCollection',
            'service_name' => 'Kategori',
        ),
        'Inventory\\V1\\Rest\\Satuan\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\Satuan\\SatuanResource',
            'route_name' => 'inventory.rest.satuan',
            'route_identifier_name' => 'id',
            'collection_name' => 'satuan',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'ID',
                1 => 'NAMA',
                2 => 'DESKRIPSI',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\Satuan\\SatuanEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\Satuan\\SatuanCollection',
            'service_name' => 'Satuan',
        ),
        'Inventory\\V1\\Rest\\Penyedia\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\Penyedia\\PenyediaResource',
            'route_name' => 'inventory.rest.penyedia',
            'route_identifier_name' => 'id',
            'collection_name' => 'penyedia',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'NAMA',
                1 => 'ALAMAT',
                2 => 'TELEPON',
                3 => 'QUERY',
                4 => 'start',
                5 => 'limit',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\Penyedia\\PenyediaEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\Penyedia\\PenyediaCollection',
            'service_name' => 'Penyedia',
        ),
        'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\BarangRuangan\\BarangRuanganResource',
            'route_name' => 'inventory.rest.barang-ruangan',
            'route_identifier_name' => 'ruangan',
            'collection_name' => 'barang_ruangan',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'RUANGAN',
                1 => 'BARANG',
                2 => 'STATUS',
                3 => 'start',
                4 => 'limit',
                5 => 'QUERY',
                6 => 'KATEGORI',
                7 => 'KATEGORI_BARANG',
                8 => 'CEKSTOK',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\BarangRuangan\\BarangRuanganEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\BarangRuangan\\BarangRuanganCollection',
            'service_name' => 'barangRuangan',
        ),
        'Inventory\\V1\\Rest\\Penerimaan\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\Penerimaan\\PenerimaanResource',
            'route_name' => 'inventory.rest.penerimaan',
            'route_identifier_name' => 'id',
            'collection_name' => 'penerimaan',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'NOMOR',
                1 => 'JENIS',
                2 => 'REF',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\Penerimaan\\PenerimaanEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\Penerimaan\\PenerimaanCollection',
            'service_name' => 'Penerimaan',
        ),
        'Inventory\\V1\\Rest\\Permintaan\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\Permintaan\\PermintaanResource',
            'route_name' => 'inventory.rest.permintaan',
            'route_identifier_name' => 'id',
            'collection_name' => 'permintaan',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'NOMOR',
                1 => 'ASAL',
                2 => 'TUJUAN',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
                6 => 'TERIMA',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\Permintaan\\PermintaanEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\Permintaan\\PermintaanCollection',
            'service_name' => 'Permintaan',
        ),
        'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PermintaanDetil\\PermintaanDetilResource',
            'route_name' => 'inventory.rest.permintaan-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'permintaan_detil',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'PERMINTAAN',
                1 => 'BARANG',
                2 => 'JUMLAH',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PermintaanDetil\\PermintaanDetilEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PermintaanDetil\\PermintaanDetilCollection',
            'service_name' => 'PermintaanDetil',
        ),
        'Inventory\\V1\\Rest\\Pengiriman\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\Pengiriman\\PengirimanResource',
            'route_name' => 'inventory.rest.pengiriman',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengiriman',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'NOMOR',
                1 => 'ASAL',
                2 => 'TUJUAN',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
                6 => 'PERMINTAAN',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\Pengiriman\\PengirimanEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\Pengiriman\\PengirimanCollection',
            'service_name' => 'Pengiriman',
        ),
        'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PengirimanDetil\\PengirimanDetilResource',
            'route_name' => 'inventory.rest.pengiriman-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengiriman_detil',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'PENGIRIMAN',
                1 => 'PERMINTAAN_BARANG_DETIL',
                2 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PengirimanDetil\\PengirimanDetilEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PengirimanDetil\\PengirimanDetilCollection',
            'service_name' => 'PengirimanDetil',
        ),
        'Inventory\\V1\\Rest\\HargaBarang\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\HargaBarang\\HargaBarangResource',
            'route_name' => 'inventory.rest.harga-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'harga_barang',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'BARANG',
                1 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\HargaBarang\\HargaBarangEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\HargaBarang\\HargaBarangCollection',
            'service_name' => 'HargaBarang',
        ),
        'Inventory\\V1\\Rest\\StokOpname\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\StokOpname\\StokOpnameResource',
            'route_name' => 'inventory.rest.stok-opname',
            'route_identifier_name' => 'id',
            'collection_name' => 'stok_opname',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'RUANGAN',
                1 => 'TANGGAL',
                2 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\StokOpname\\StokOpnameEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\StokOpname\\StokOpnameCollection',
            'service_name' => 'StokOpname',
        ),
        'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\StokOpnameDetil\\StokOpnameDetilResource',
            'route_name' => 'inventory.rest.stok-opname-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'stok_opname_detil',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'STOK_OPNAME',
                1 => 'BARANG_RUANGAN',
                2 => 'TANGGAL',
                3 => 'QUERY',
                4 => 'KATEGORI',
                5 => 'start',
                6 => 'limit',
                7 => 'MANUAL',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\StokOpnameDetil\\StokOpnameDetilEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\StokOpnameDetil\\StokOpnameDetilCollection',
            'service_name' => 'StokOpnameDetil',
        ),
        'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\TransaksiStokRuangan\\TransaksiStokRuanganResource',
            'route_name' => 'inventory.rest.transaksi-stok-ruangan',
            'route_identifier_name' => 'id',
            'collection_name' => 'transaksi_stok_ruangan',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'BARANG_RUANGAN',
                1 => 'JENIS',
                2 => 'FLAG',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\TransaksiStokRuangan\\TransaksiStokRuanganEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\TransaksiStokRuangan\\TransaksiStokRuanganCollection',
            'service_name' => 'TransaksiStokRuangan',
        ),
        'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PenerimaanBarang\\PenerimaanBarangResource',
            'route_name' => 'inventory.rest.penerimaan-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'penerimaan_barang',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'ID',
                1 => 'FAKTUR',
                2 => 'REKANAN',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
            ),
            'page_size' => '25',
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PenerimaanBarang\\PenerimaanBarangEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PenerimaanBarang\\PenerimaanBarangCollection',
            'service_name' => 'PenerimaanBarang',
        ),
        'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\PenerimaanBarangDetilResource',
            'route_name' => 'inventory.rest.penerimaan-barang-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'penerimaan_barang_detil',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'PENERIMAAN',
                1 => 'BARANG',
                2 => 'NO_BATCH',
                3 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\PenerimaanBarangDetilEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\PenerimaanBarangDetilCollection',
            'service_name' => 'PenerimaanBarangDetil',
        ),
        'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PengembalianBarang\\PengembalianBarangResource',
            'route_name' => 'inventory.rest.pengembalian-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengembalian_barang',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'REKANAN',
                1 => 'TANGGAL',
                2 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PengembalianBarang\\PengembalianBarangEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PengembalianBarang\\PengembalianBarangCollection',
            'service_name' => 'PengembalianBarang',
        ),
        'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PengembalianBarangDetil\\PengembalianBarangDetilResource',
            'route_name' => 'inventory.rest.pengembalian-barang-detil',
            'route_identifier_name' => 'id',
            'collection_name' => 'pengembalian_barang_detil',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'PENGEMBALIAN',
                1 => 'BARANG',
                2 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PengembalianBarangDetil\\PengembalianBarangDetilEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PengembalianBarangDetil\\PengembalianBarangDetilCollection',
            'service_name' => 'PengembalianBarangDetil',
        ),
        'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\PembatalanPenerimaanBarangResource',
            'route_name' => 'inventory.rest.pembatalan-penerimaan-barang',
            'route_identifier_name' => 'id',
            'collection_name' => 'pembatalan_penerimaan_barang',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'PENERIMAAN_BARANG',
                1 => 'JENIS',
                2 => 'STATUS',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\PembatalanPenerimaanBarangEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\PembatalanPenerimaanBarangCollection',
            'service_name' => 'PembatalanPenerimaanBarang',
        ),
        'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\StokBarangMinimum\\StokBarangMinimumResource',
            'route_name' => 'inventory.rest.stok-barang-minimum',
            'route_identifier_name' => 'id',
            'collection_name' => 'stok_barang_minimum',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'QUERY',
                1 => 'start',
                2 => 'limit',
            ),
            'page_size' => '25',
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\StokBarangMinimum\\StokBarangMinimumEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\StokBarangMinimum\\StokBarangMinimumCollection',
            'service_name' => 'StokBarangMinimum',
        ),
        'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => array(
            'listener' => 'Inventory\\V1\\Rest\\PaketFarmasi\\PaketFarmasiResource',
            'route_name' => 'inventory.rest.paket-farmasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'paket_farmasi',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(
                0 => 'BARANG',
                1 => 'TINDAKAN',
                2 => 'QUERY',
                3 => 'STATUS',
                4 => 'start',
                5 => 'limit',
            ),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'Inventory\\V1\\Rest\\PaketFarmasi\\PaketFarmasiEntity',
            'collection_class' => 'Inventory\\V1\\Rest\\PaketFarmasi\\PaketFarmasiCollection',
            'service_name' => 'PaketFarmasi',
        ),
    ),
    'zf-content-negotiation' => array(
        'controllers' => array(
            'Inventory\\V1\\Rest\\Barang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Kategori\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Satuan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Penyedia\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Penerimaan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Permintaan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\Pengiriman\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\HargaBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\StokOpname\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => 'Json',
            'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => 'Json',
        ),
        'accept_whitelist' => array(
            'Inventory\\V1\\Rest\\Barang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Kategori\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Satuan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Penyedia\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Penerimaan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Permintaan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Pengiriman\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\HargaBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\StokOpname\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
        ),
        'content_type_whitelist' => array(
            'Inventory\\V1\\Rest\\Barang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Kategori\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Satuan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Penyedia\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\BarangRuangan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Penerimaan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Permintaan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PermintaanDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\Pengiriman\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PengirimanDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\HargaBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\StokOpname\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\StokOpnameDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PengembalianBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\StokBarangMinimum\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
            'Inventory\\V1\\Rest\\PaketFarmasi\\Controller' => array(
                0 => 'application/vnd.inventory.v1+json',
                1 => 'application/json',
            ),
        ),
    ),
    'zf-hal' => array(
        'metadata_map' => array(
            'Inventory\\V1\\Rest\\Barang\\BarangEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\Barang\\BarangCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\Kategori\\KategoriEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.kategori',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\Kategori\\KategoriCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.kategori',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\Satuan\\SatuanEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.satuan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\Satuan\\SatuanCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.satuan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\Penyedia\\PenyediaEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penyedia',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\Penyedia\\PenyediaCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penyedia',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\BarangRuangan\\BarangRuanganEntity' => array(
                'entity_identifier_name' => 'RUANGAN',
                'route_name' => 'inventory.rest.barang-ruangan',
                'route_identifier_name' => 'ruangan',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\BarangRuangan\\BarangRuanganCollection' => array(
                'entity_identifier_name' => 'RUANGAN',
                'route_name' => 'inventory.rest.barang-ruangan',
                'route_identifier_name' => 'ruangan',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\Penerimaan\\PenerimaanEntity' => array(
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.penerimaan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\Penerimaan\\PenerimaanCollection' => array(
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.penerimaan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\Permintaan\\PermintaanEntity' => array(
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.permintaan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\Permintaan\\PermintaanCollection' => array(
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.permintaan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PermintaanDetil\\PermintaanDetilEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.permintaan-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PermintaanDetil\\PermintaanDetilCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.permintaan-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\Pengiriman\\PengirimanEntity' => array(
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.pengiriman',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\Pengiriman\\PengirimanCollection' => array(
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'inventory.rest.pengiriman',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PengirimanDetil\\PengirimanDetilEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengiriman-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PengirimanDetil\\PengirimanDetilCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengiriman-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\HargaBarang\\HargaBarangEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.harga-barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\HargaBarang\\HargaBarangCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.harga-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\StokOpname\\StokOpnameEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\StokOpname\\StokOpnameCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\StokOpnameDetil\\StokOpnameDetilEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\StokOpnameDetil\\StokOpnameDetilCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-opname-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\TransaksiStokRuanganEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.transaksi-stok-ruangan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\TransaksiStokRuangan\\TransaksiStokRuanganCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.transaksi-stok-ruangan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarang\\PenerimaanBarangEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarang\\PenerimaanBarangCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\PenerimaanBarangDetilEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PenerimaanBarangDetil\\PenerimaanBarangDetilCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.penerimaan-barang-detil',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PengembalianBarang\\PengembalianBarangEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengembalian-barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PengembalianBarang\\PengembalianBarangCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengembalian-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\PengembalianBarangDetilEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pengembalian-barang-detil',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PengembalianBarangDetil\\PengembalianBarangDetilCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'inventory.rest.pengembalian-barang-detil',
                'route_identifier_name' => 'pengembalian_barang_detil_id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\PembatalanPenerimaanBarangEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pembatalan-penerimaan-barang',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PembatalanPenerimaanBarang\\PembatalanPenerimaanBarangCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.pembatalan-penerimaan-barang',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\StokBarangMinimum\\StokBarangMinimumEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-barang-minimum',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\StokBarangMinimum\\StokBarangMinimumCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.stok-barang-minimum',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
            'Inventory\\V1\\Rest\\PaketFarmasi\\PaketFarmasiEntity' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.paket-farmasi',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Hydrator\\ArraySerializable',
            ),
            'Inventory\\V1\\Rest\\PaketFarmasi\\PaketFarmasiCollection' => array(
                'entity_identifier_name' => 'ID',
                'route_name' => 'inventory.rest.paket-farmasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ),
        ),
    ),
);
