<?php
return [
    'router' => [
        'routes' => [
            'layanan.rest.tindakan-medis' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/tindakanmedis[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\TindakanMedis\\Controller',
                    ],
                ],
            ],
            'layanan.rest.petugas-tindakan-medis' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/petugastindakanmedis[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\PetugasTindakanMedis\\Controller',
                    ],
                ],
            ],
            'layanan.rest.order-rad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/orderrad[/:nomor]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\OrderRad\\Controller',
                    ],
                ],
            ],
            'layanan.rest.order-detil-rad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/orderdetilrad[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\OrderDetilRad\\Controller',
                    ],
                ],
            ],
            'layanan.rest.order-lab' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/orderlab[/:nomor]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\OrderLab\\Controller',
                    ],
                ],
            ],
            'layanan.rest.order-detil-lab' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/orderdetillab[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\OrderDetilLab\\Controller',
                    ],
                ],
            ],
            'layanan.rest.hasil-rad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/hasilrad[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\HasilRad\\Controller',
                    ],
                ],
            ],
            'layanan.rest.order-resep' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/orderresep[/:nomor]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\OrderResep\\Controller',
                    ],
                ],
            ],
            'layanan.rest.order-detil-resep' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/orderdetilresep[/:order_id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\OrderDetilResep\\Controller',
                    ],
                ],
            ],
            'layanan.rest.hasil-lab' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/hasillab[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\HasilLab\\Controller',
                    ],
                ],
            ],
            'layanan.rest.farmasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/farmasi[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\Farmasi\\Controller',
                    ],
                ],
            ],
            'layanan.rest.o2' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/o2[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\O2\\Controller',
                    ],
                ],
            ],
            'layanan.rest.pasien-pulang' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/pasienpulang[/:kunjungan]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\PasienPulang\\Controller',
                    ],
                ],
            ],
            'layanan.rest.pasien-meninggal' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/pasienmeninggal[/:kunjungan]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\PasienMeninggal\\Controller',
                    ],
                ],
            ],
            'layanan.rest.catatan-hasil-lab' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/catatanhasillab[/:kunjungan]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\CatatanHasilLab\\Controller',
                    ],
                ],
            ],
            'layanan.rest.retur-farmasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/returfarmasi[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\ReturFarmasi\\Controller',
                    ],
                ],
            ],
            'layanan.rest.hasil-pa' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/hasilpa[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\HasilPa\\Controller',
                    ],
                ],
            ],
            'layanan.rest.viewer-rad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/viewerad[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\ViewerRad\\Controller',
                    ],
                ],
            ],
            'layanan.rest.kelahiran' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/kelahiran[/:kelahiran_id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\Kelahiran\\Controller',
                    ],
                ],
            ],
            'layanan.rest.jasa-tuslah-farmasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/layanan/jasatuslahfarmasi[/:id]',
                    'defaults' => [
                        'controller' => 'Layanan\\V1\\Rest\\JasaTuslahFarmasi\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'layanan.rest.tindakan-medis',
            1 => 'layanan.rest.petugas-tindakan-medis',
            2 => 'layanan.rest.order-rad',
            3 => 'layanan.rest.order-detil-rad',
            4 => 'layanan.rest.order-lab',
            5 => 'layanan.rest.order-detil-lab',
            6 => 'layanan.rest.order-detil-lab',
            7 => 'layanan.rest.hasil-rad',
            8 => 'layanan.rest.order-resep',
            9 => 'layanan.rest.order-detil-resep',
            10 => 'layanan.rest.hasil-lab',
            11 => 'layanan.rest.farmasi',
            12 => 'layanan.rest.o2',
            13 => 'layanan.rest.pasien-pulang',
            14 => 'layanan.rest.pasien-meninggal',
            15 => 'layanan.rest.catatan-hasil-lab',
            16 => 'layanan.rest.retur-farmasi',
            17 => 'layanan.rest.hasil-pa',
            18 => 'layanan.rest.hasil-pa',
            19 => 'layanan.rest.viewer-rad',
            20 => 'layanan.rest.kelahiran',
            21 => 'layanan.rest.jasa-tuslah-farmasi',
        ],
    ],
    'service_manager' => [
        'factories' => [
            \Layanan\V1\Rest\TindakanMedis\TindakanMedisResource::class => \Layanan\V1\Rest\TindakanMedis\TindakanMedisResourceFactory::class,
            \Layanan\V1\Rest\PetugasTindakanMedis\PetugasTindakanMedisResource::class => \Layanan\V1\Rest\PetugasTindakanMedis\PetugasTindakanMedisResourceFactory::class,
            \Layanan\V1\Rest\OrderRad\OrderRadResource::class => \Layanan\V1\Rest\OrderRad\OrderRadResourceFactory::class,
            \Layanan\V1\Rest\OrderDetilRad\OrderDetilRadResource::class => \Layanan\V1\Rest\OrderDetilRad\OrderDetilRadResourceFactory::class,
            \Layanan\V1\Rest\OrderLab\OrderLabResource::class => \Layanan\V1\Rest\OrderLab\OrderLabResourceFactory::class,
            \Layanan\V1\Rest\OrderDetilLab\OrderDetilLabResource::class => \Layanan\V1\Rest\OrderDetilLab\OrderDetilLabResourceFactory::class,
            \Layanan\V1\Rest\HasilRad\HasilRadResource::class => \Layanan\V1\Rest\HasilRad\HasilRadResourceFactory::class,
            \Layanan\V1\Rest\OrderResep\OrderResepResource::class => \Layanan\V1\Rest\OrderResep\OrderResepResourceFactory::class,
            \Layanan\V1\Rest\OrderDetilResep\OrderDetilResepResource::class => \Layanan\V1\Rest\OrderDetilResep\OrderDetilResepResourceFactory::class,
            \Layanan\V1\Rest\HasilLab\HasilLabResource::class => \Layanan\V1\Rest\HasilLab\HasilLabResourceFactory::class,
            \Layanan\V1\Rest\Farmasi\FarmasiResource::class => \Layanan\V1\Rest\Farmasi\FarmasiResourceFactory::class,
            \Layanan\V1\Rest\O2\O2Resource::class => \Layanan\V1\Rest\O2\O2ResourceFactory::class,
            \Layanan\V1\Rest\PasienPulang\PasienPulangResource::class => \Layanan\V1\Rest\PasienPulang\PasienPulangResourceFactory::class,
            \Layanan\V1\Rest\PasienMeninggal\PasienMeninggalResource::class => \Layanan\V1\Rest\PasienMeninggal\PasienMeninggalResourceFactory::class,
            \Layanan\V1\Rest\CatatanHasilLab\CatatanHasilLabResource::class => \Layanan\V1\Rest\CatatanHasilLab\CatatanHasilLabResourceFactory::class,
            \Layanan\V1\Rest\ReturFarmasi\ReturFarmasiResource::class => \Layanan\V1\Rest\ReturFarmasi\ReturFarmasiResourceFactory::class,
            \Layanan\V1\Rest\HasilPa\HasilPaResource::class => \Layanan\V1\Rest\HasilPa\HasilPaResourceFactory::class,
            \Layanan\V1\Rest\ViewerRad\ViewerRadResource::class => \Layanan\V1\Rest\ViewerRad\ViewerRadResourceFactory::class,
            \Layanan\V1\Rest\Kelahiran\KelahiranResource::class => \Layanan\V1\Rest\Kelahiran\KelahiranResourceFactory::class,
            \Layanan\V1\Rest\JasaTuslahFarmasi\JasaTuslahFarmasiResource::class => \Layanan\V1\Rest\JasaTuslahFarmasi\JasaTuslahFarmasiResourceFactory::class,
        ],
    ],
    'zf-rest' => [
        'Layanan\\V1\\Rest\\TindakanMedis\\Controller' => [
            'listener' => \Layanan\V1\Rest\TindakanMedis\TindakanMedisResource::class,
            'route_name' => 'layanan.rest.tindakan-medis',
            'route_identifier_name' => 'id',
            'collection_name' => 'tindakan_medis',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'RUANGAN',
                2 => 'STATUS',
                3 => 'KUNJUNGAN',
                4 => 'COLUMNS',
                5 => 'REFERENSI',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\TindakanMedis\TindakanMedisEntity::class,
            'collection_class' => \Layanan\V1\Rest\TindakanMedis\TindakanMedisCollection::class,
            'service_name' => 'TindakanMedis',
        ],
        'Layanan\\V1\\Rest\\PetugasTindakanMedis\\Controller' => [
            'listener' => \Layanan\V1\Rest\PetugasTindakanMedis\PetugasTindakanMedisResource::class,
            'route_name' => 'layanan.rest.petugas-tindakan-medis',
            'route_identifier_name' => 'id',
            'collection_name' => 'petugas_tindakan_medis',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TINDAKAN_MEDIS',
                1 => 'STATUS',
                2 => 'KUNJUNGAN',
                3 => 'DOKTER',
                4 => 'SHOW_TINDAKAN_JASA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\PetugasTindakanMedis\PetugasTindakanMedisEntity::class,
            'collection_class' => \Layanan\V1\Rest\PetugasTindakanMedis\PetugasTindakanMedisCollection::class,
            'service_name' => 'PetugasTindakanMedis',
        ],
        'Layanan\\V1\\Rest\\OrderRad\\Controller' => [
            'listener' => \Layanan\V1\Rest\OrderRad\OrderRadResource::class,
            'route_name' => 'layanan.rest.order-rad',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'order_rad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'NOPEN',
                2 => 'ASAL',
                3 => 'TANGGAL',
                4 => 'TUJUAN',
                5 => 'STATUS',
                6 => 'KUNJUNGAN',
                7 => 'HISTORY',
                8 => 'COLUMNS',
                9 => 'REFERENSI',
                10 => 'NORM',
                11 => 'start',
                12 => 'limit',
                13 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\OrderRad\OrderRadEntity::class,
            'collection_class' => \Layanan\V1\Rest\OrderRad\OrderRadCollection::class,
            'service_name' => 'OrderRad',
        ],
        'Layanan\\V1\\Rest\\OrderDetilRad\\Controller' => [
            'listener' => \Layanan\V1\Rest\OrderDetilRad\OrderDetilRadResource::class,
            'route_name' => 'layanan.rest.order-detil-rad',
            'route_identifier_name' => 'id',
            'collection_name' => 'order_detil_rad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ORDER_ID',
                1 => 'TINDAKAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\OrderDetilRad\OrderDetilRadEntity::class,
            'collection_class' => \Layanan\V1\Rest\OrderDetilRad\OrderDetilRadCollection::class,
            'service_name' => 'OrderDetilRad',
        ],
        'Layanan\\V1\\Rest\\OrderLab\\Controller' => [
            'listener' => \Layanan\V1\Rest\OrderLab\OrderLabResource::class,
            'route_name' => 'layanan.rest.order-lab',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'order_lab',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'NOPEN',
                2 => 'ASAL',
                3 => 'TUJUAN',
                4 => 'STATUS',
                5 => 'KUNJUNGAN',
                6 => 'HISTORY',
                7 => 'TANGGAL',
                8 => 'COLUMNS',
                9 => 'REFERENSI',
                10 => 'NORM',
                11 => 'start',
                12 => 'limit',
                13 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\OrderLab\OrderLabEntity::class,
            'collection_class' => \Layanan\V1\Rest\OrderLab\OrderLabCollection::class,
            'service_name' => 'OrderLab',
        ],
        'Layanan\\V1\\Rest\\OrderDetilLab\\Controller' => [
            'listener' => \Layanan\V1\Rest\OrderDetilLab\OrderDetilLabResource::class,
            'route_name' => 'layanan.rest.order-detil-lab',
            'route_identifier_name' => 'id',
            'collection_name' => 'order_detil_lab',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ORDER_ID',
                1 => 'TINDAKAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\OrderDetilLab\OrderDetilLabEntity::class,
            'collection_class' => \Layanan\V1\Rest\OrderDetilLab\OrderDetilLabCollection::class,
            'service_name' => 'OrderDetilLab',
        ],
        'Layanan\\V1\\Rest\\HasilRad\\Controller' => [
            'listener' => \Layanan\V1\Rest\HasilRad\HasilRadResource::class,
            'route_name' => 'layanan.rest.hasil-rad',
            'route_identifier_name' => 'id',
            'collection_name' => 'hasil_rad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TANGGAL',
                1 => 'KLINIS',
                2 => 'TINDAKAN_MEDIS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\HasilRad\HasilRadEntity::class,
            'collection_class' => \Layanan\V1\Rest\HasilRad\HasilRadCollection::class,
            'service_name' => 'HasilRad',
        ],
        'Layanan\\V1\\Rest\\OrderResep\\Controller' => [
            'listener' => \Layanan\V1\Rest\OrderResep\OrderResepResource::class,
            'route_name' => 'layanan.rest.order-resep',
            'route_identifier_name' => 'nomor',
            'collection_name' => 'order_resep',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
                4 => 'POST',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOMOR',
                1 => 'NOPEN',
                2 => 'ASAL',
                3 => 'TANGGAL',
                4 => 'DOKTER_DPJP',
                5 => 'STATUS',
                6 => 'limit',
                7 => 'start',
                8 => 'KUNJUNGAN',
                9 => 'HISTORY',
                10 => 'COLUMNS',
                11 => 'REFERENSI',
                12 => 'NORM',
                13 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\OrderResep\OrderResepEntity::class,
            'collection_class' => \Layanan\V1\Rest\OrderResep\OrderResepCollection::class,
            'service_name' => 'OrderResep',
        ],
        'Layanan\\V1\\Rest\\OrderDetilResep\\Controller' => [
            'listener' => \Layanan\V1\Rest\OrderDetilResep\OrderDetilResepResource::class,
            'route_name' => 'layanan.rest.order-detil-resep',
            'route_identifier_name' => 'order_id',
            'collection_name' => 'order_detil_resep',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ORDER_ID',
                1 => 'FARMASI',
                2 => 'JUMLAH',
                3 => 'ATURAN_PAKAI',
                4 => 'limit',
                5 => 'start',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\OrderDetilResep\OrderDetilResepEntity::class,
            'collection_class' => \Layanan\V1\Rest\OrderDetilResep\OrderDetilResepCollection::class,
            'service_name' => 'OrderDetilResep',
        ],
        'Layanan\\V1\\Rest\\HasilLab\\Controller' => [
            'listener' => \Layanan\V1\Rest\HasilLab\HasilLabResource::class,
            'route_name' => 'layanan.rest.hasil-lab',
            'route_identifier_name' => 'id',
            'collection_name' => 'hasil_lab',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TINDAKAN_MEDIS',
                1 => 'PARAMETER_TINDAKAN',
                2 => 'TANGGAL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\HasilLab\HasilLabEntity::class,
            'collection_class' => \Layanan\V1\Rest\HasilLab\HasilLabCollection::class,
            'service_name' => 'HasilLab',
        ],
        'Layanan\\V1\\Rest\\Farmasi\\Controller' => [
            'listener' => \Layanan\V1\Rest\Farmasi\FarmasiResource::class,
            'route_name' => 'layanan.rest.farmasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'farmasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'FARMASI',
                2 => 'TANGGAL',
                3 => 'NORM',
                4 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\Farmasi\FarmasiEntity::class,
            'collection_class' => \Layanan\V1\Rest\Farmasi\FarmasiCollection::class,
            'service_name' => 'Farmasi',
        ],
        'Layanan\\V1\\Rest\\O2\\Controller' => [
            'listener' => \Layanan\V1\Rest\O2\O2Resource::class,
            'route_name' => 'layanan.rest.o2',
            'route_identifier_name' => 'id',
            'collection_name' => 'o2',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'FLOW',
                2 => 'PASANG',
                3 => 'LEPAS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\O2\O2Entity::class,
            'collection_class' => \Layanan\V1\Rest\O2\O2Collection::class,
            'service_name' => 'O2',
        ],
        'Layanan\\V1\\Rest\\PasienPulang\\Controller' => [
            'listener' => \Layanan\V1\Rest\PasienPulang\PasienPulangResource::class,
            'route_name' => 'layanan.rest.pasien-pulang',
            'route_identifier_name' => 'kunjungan',
            'collection_name' => 'pasien_pulang',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'TANGGAL',
                2 => 'CARA',
                3 => 'DIAGNOSA',
                4 => 'REFERENSI',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\PasienPulang\PasienPulangEntity::class,
            'collection_class' => \Layanan\V1\Rest\PasienPulang\PasienPulangCollection::class,
            'service_name' => 'PasienPulang',
        ],
        'Layanan\\V1\\Rest\\PasienMeninggal\\Controller' => [
            'listener' => \Layanan\V1\Rest\PasienMeninggal\PasienMeninggalResource::class,
            'route_name' => 'layanan.rest.pasien-meninggal',
            'route_identifier_name' => 'kunjungan',
            'collection_name' => 'pasien_meninggal',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'TANGGAL',
                2 => 'DIAGNOSA',
                3 => 'DOKTER',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\PasienMeninggal\PasienMeninggalEntity::class,
            'collection_class' => \Layanan\V1\Rest\PasienMeninggal\PasienMeninggalCollection::class,
            'service_name' => 'PasienMeninggal',
        ],
        'Layanan\\V1\\Rest\\CatatanHasilLab\\Controller' => [
            'listener' => \Layanan\V1\Rest\CatatanHasilLab\CatatanHasilLabResource::class,
            'route_name' => 'layanan.rest.catatan-hasil-lab',
            'route_identifier_name' => 'kunjungan',
            'collection_name' => 'catatan_hasil_lab',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'TANGGAL',
                2 => 'DOKTER',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\CatatanHasilLab\CatatanHasilLabEntity::class,
            'collection_class' => \Layanan\V1\Rest\CatatanHasilLab\CatatanHasilLabCollection::class,
            'service_name' => 'CatatanHasilLab',
        ],
        'Layanan\\V1\\Rest\\ReturFarmasi\\Controller' => [
            'listener' => \Layanan\V1\Rest\ReturFarmasi\ReturFarmasiResource::class,
            'route_name' => 'layanan.rest.retur-farmasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'retur_farmasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'OLEH',
                1 => 'ID_FARMASI',
                2 => 'SUM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\ReturFarmasi\ReturFarmasiEntity::class,
            'collection_class' => \Layanan\V1\Rest\ReturFarmasi\ReturFarmasiCollection::class,
            'service_name' => 'ReturFarmasi',
        ],
        'Layanan\\V1\\Rest\\HasilPa\\Controller' => [
            'listener' => \Layanan\V1\Rest\HasilPa\HasilPaResource::class,
            'route_name' => 'layanan.rest.hasil-pa',
            'route_identifier_name' => 'id',
            'collection_name' => 'hasil_pa',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'KUNJUNGAN',
                2 => 'JENIS_PEMERIKSAAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\HasilPa\HasilPaEntity::class,
            'collection_class' => \Layanan\V1\Rest\HasilPa\HasilPaCollection::class,
            'service_name' => 'HasilPa',
        ],
        'Layanan\\V1\\Rest\\ViewerRad\\Controller' => [
            'listener' => \Layanan\V1\Rest\ViewerRad\ViewerRadResource::class,
            'route_name' => 'layanan.rest.viewer-rad',
            'route_identifier_name' => 'id',
            'collection_name' => 'viewer_rad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'TINDAKAN_MEDIS',
                1 => 'DATA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\ViewerRad\ViewerRadEntity::class,
            'collection_class' => \Layanan\V1\Rest\ViewerRad\ViewerRadCollection::class,
            'service_name' => 'ViewerRad',
        ],
        'Layanan\\V1\\Rest\\Kelahiran\\Controller' => [
            'listener' => \Layanan\V1\Rest\Kelahiran\KelahiranResource::class,
            'route_name' => 'layanan.rest.kelahiran',
            'route_identifier_name' => 'kelahiran_id',
            'collection_name' => 'kelahiran',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'start',
                1 => 'limit',
                2 => 'TANGGAL',
                3 => 'NOPEN',
                4 => 'KUNJUNGAN',
                5 => 'NAMA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\Kelahiran\KelahiranEntity::class,
            'collection_class' => \Layanan\V1\Rest\Kelahiran\KelahiranCollection::class,
            'service_name' => 'Kelahiran',
        ],
        'Layanan\\V1\\Rest\\JasaTuslahFarmasi\\Controller' => [
            'listener' => \Layanan\V1\Rest\JasaTuslahFarmasi\JasaTuslahFarmasiResource::class,
            'route_name' => 'layanan.rest.jasa-tuslah-farmasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'jasa_tuslah_farmasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'FARMASI',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Layanan\V1\Rest\JasaTuslahFarmasi\JasaTuslahFarmasiEntity::class,
            'collection_class' => \Layanan\V1\Rest\JasaTuslahFarmasi\JasaTuslahFarmasiCollection::class,
            'service_name' => 'JasaTuslahFarmasi',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'Layanan\\V1\\Rest\\TindakanMedis\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\PetugasTindakanMedis\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\OrderRad\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\OrderDetilRad\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\OrderLab\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\OrderDetilLab\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\HasilRad\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\OrderResep\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\OrderDetilResep\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\HasilLab\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\Farmasi\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\O2\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\PasienPulang\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\PasienMeninggal\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\CatatanHasilLab\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\ReturFarmasi\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\HasilPa\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\ViewerRad\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\Kelahiran\\Controller' => 'Json',
            'Layanan\\V1\\Rest\\JasaTuslahFarmasi\\Controller' => 'Json',
        ],
        'accept_whitelist' => [
            'Layanan\\V1\\Rest\\TindakanMedis\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\PetugasTindakanMedis\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderDetilRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderDetilLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\HasilRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderResep\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderDetilResep\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\HasilLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\Farmasi\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\O2\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\PasienPulang\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\PasienMeninggal\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\CatatanHasilLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\ReturFarmasi\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\HasilPa\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\ViewerRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\Kelahiran\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\JasaTuslahFarmasi\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Layanan\\V1\\Rest\\TindakanMedis\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\PetugasTindakanMedis\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderDetilRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderDetilLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\HasilRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderResep\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\OrderDetilResep\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\HasilLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\Farmasi\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\O2\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\PasienPulang\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\PasienMeninggal\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\CatatanHasilLab\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\ReturFarmasi\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\HasilPa\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\ViewerRad\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\Kelahiran\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
            'Layanan\\V1\\Rest\\JasaTuslahFarmasi\\Controller' => [
                0 => 'application/vnd.layanan.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \Layanan\V1\Rest\TindakanMedis\TindakanMedisEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.tindakan-medis',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\TindakanMedis\TindakanMedisCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.tindakan-medis',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\PetugasTindakanMedis\PetugasTindakanMedisEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.petugas-tindakan-medis',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\PetugasTindakanMedis\PetugasTindakanMedisCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.petugas-tindakan-medis',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\OrderRad\OrderRadEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'layanan.rest.order-rad',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\OrderRad\OrderRadCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'layanan.rest.order-rad',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\OrderDetilRad\OrderDetilRadEntity::class => [
                'entity_identifier_name' => 'ORDER_ID',
                'route_name' => 'layanan.rest.order-detil-rad',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\OrderDetilRad\OrderDetilRadCollection::class => [
                'entity_identifier_name' => 'ORDER_ID',
                'route_name' => 'layanan.rest.order-detil-rad',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\OrderLab\OrderLabEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'layanan.rest.order-lab',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\OrderLab\OrderLabCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'layanan.rest.order-lab',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\OrderDetilLab\OrderDetilLabEntity::class => [
                'entity_identifier_name' => 'ORDER_ID',
                'route_name' => 'layanan.rest.order-detil-lab',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\OrderDetilLab\OrderDetilLabCollection::class => [
                'entity_identifier_name' => 'ORDER_ID',
                'route_name' => 'layanan.rest.order-detil-lab',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\HasilRad\HasilRadEntity::class => [
                'entity_identifier_name' => 'TINDAKAN_MEDIS',
                'route_name' => 'layanan.rest.hasil-rad',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\HasilRad\HasilRadCollection::class => [
                'entity_identifier_name' => 'TINDAKAN_MEDIS',
                'route_name' => 'layanan.rest.hasil-rad',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\OrderResep\OrderResepEntity::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'layanan.rest.order-resep',
                'route_identifier_name' => 'nomor',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\OrderResep\OrderResepCollection::class => [
                'entity_identifier_name' => 'NOMOR',
                'route_name' => 'layanan.rest.order-resep',
                'route_identifier_name' => 'nomor',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\OrderDetilResep\OrderDetilResepEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'layanan.rest.order-detil-resep',
                'route_identifier_name' => 'order_id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\OrderDetilResep\OrderDetilResepCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'layanan.rest.order-detil-resep',
                'route_identifier_name' => 'order_id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\HasilLab\HasilLabEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.hasil-lab',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\HasilLab\HasilLabCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.hasil-lab',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\Farmasi\FarmasiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.farmasi',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\Farmasi\FarmasiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.farmasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\O2\O2Entity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.o2',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\O2\O2Collection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.o2',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\PasienPulang\PasienPulangEntity::class => [
                'entity_identifier_name' => 'KUNJUNGAN',
                'route_name' => 'layanan.rest.pasien-pulang',
                'route_identifier_name' => 'kunjungan',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\PasienPulang\PasienPulangCollection::class => [
                'entity_identifier_name' => 'KUNJUNGAN',
                'route_name' => 'layanan.rest.pasien-pulang',
                'route_identifier_name' => 'kunjungan',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\PasienMeninggal\PasienMeninggalEntity::class => [
                'entity_identifier_name' => 'KUNJUNGAN',
                'route_name' => 'layanan.rest.pasien-meninggal',
                'route_identifier_name' => 'kunjungan',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\PasienMeninggal\PasienMeninggalCollection::class => [
                'entity_identifier_name' => 'KUNJUNGAN',
                'route_name' => 'layanan.rest.pasien-meninggal',
                'route_identifier_name' => 'kunjungan',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\CatatanHasilLab\CatatanHasilLabEntity::class => [
                'entity_identifier_name' => 'KUNJUNGAN',
                'route_name' => 'layanan.rest.catatan-hasil-lab',
                'route_identifier_name' => 'kunjungan',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\CatatanHasilLab\CatatanHasilLabCollection::class => [
                'entity_identifier_name' => 'KUNJUNGAN',
                'route_name' => 'layanan.rest.catatan-hasil-lab',
                'route_identifier_name' => 'kunjungan',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\ReturFarmasi\ReturFarmasiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.retur-farmasi',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\ReturFarmasi\ReturFarmasiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.retur-farmasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\HasilPa\HasilPaEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.hasil-pa',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \Layanan\V1\Rest\HasilPa\HasilPaCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.hasil-pa',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\ViewerRad\ViewerRadEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'layanan.rest.viewer-rad',
                'route_identifier_name' => 'id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Layanan\V1\Rest\ViewerRad\ViewerRadCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'layanan.rest.viewer-rad',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\Kelahiran\KelahiranEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'layanan.rest.kelahiran',
                'route_identifier_name' => 'kelahiran_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Layanan\V1\Rest\Kelahiran\KelahiranCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'layanan.rest.kelahiran',
                'route_identifier_name' => 'kelahiran_id',
                'is_collection' => true,
            ],
            \Layanan\V1\Rest\JasaTuslahFarmasi\JasaTuslahFarmasiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.jasa-tuslah-farmasi',
                'route_identifier_name' => 'id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Layanan\V1\Rest\JasaTuslahFarmasi\JasaTuslahFarmasiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'layanan.rest.jasa-tuslah-farmasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
        ],
    ],
];
