<?php
return [
    'router' => [
        'routes' => [
            'medical-record.rest.diagnosa' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/diagnosa[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.operasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/operasi[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Operasi\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.icd10' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/icd10[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\ICD10\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.icd9-cm' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/icd9cm[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.operasi-di-tindakan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/operasiditindakan[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.icd10-kematian' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/icd10kematian[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.anamnesis' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis[/:anamnesis_id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.pemeriksaan-fisik' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/pemeriksaan/fisik[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.riwayat-perjalanan-penyakit' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/riwayat/perjalananpenyakit[/:riwayat_perjalanan_penyakit_id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.riwayat-alergi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/riwayat/alergi[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.tanda-vital' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/pemeriksaan/umum/tandavital[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\TandaVital\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.peminjaman-berkas' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/peminjamanberkas[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.peminjaman-berkas1' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/peminjamanberkas1[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'medical-record.rest.diagnosa',
            1 => 'medical-record.rest.operasi',
            2 => 'medical-record.rest.icd10',
            3 => 'medical-record.rest.icd9-cm',
            4 => 'medical-record.rest.operasi-di-tindakan',
            5 => 'medical-record.rest.icd10-kematian',
            6 => 'medical-record.rest.anamnesis',
            7 => 'medical-record.rest.pemeriksaan-fisik',
            29 => 'medical-record.rest.riwayat-perjalanan-penyakit',
            30 => 'medical-record.rest.riwayat-alergi',
            31 => 'medical-record.rest.tanda-vital',
            32 => 'medical-record.rest.peminjaman-berkas',
            33 => 'medical-record.rest.peminjaman-berkas1',
        ],
    ],
    'service_manager' => [
        'factories' => [
            \MedicalRecord\V1\Rest\Diagnosa\DiagnosaResource::class => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaResourceFactory::class,
            \MedicalRecord\V1\Rest\Operasi\OperasiResource::class => \MedicalRecord\V1\Rest\Operasi\OperasiResourceFactory::class,
            \MedicalRecord\V1\Rest\ICD10\ICD10Resource::class => \MedicalRecord\V1\Rest\ICD10\ICD10ResourceFactory::class,
            \MedicalRecord\V1\Rest\ICD9CM\ICD9CMResource::class => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMResourceFactory::class,
            \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanResource::class => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanResourceFactory::class,
            \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianResource::class => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianResourceFactory::class,
            \MedicalRecord\V1\Rest\Anamnesis\AnamnesisResource::class => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisResourceFactory::class,
            \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikResource::class => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikResourceFactory::class,
            \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitResource::class => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitResourceFactory::class,
            \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiResource::class => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiResourceFactory::class,
            \MedicalRecord\V1\Rest\TandaVital\TandaVitalResource::class => \MedicalRecord\V1\Rest\TandaVital\TandaVitalResourceFactory::class,
            \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasResource::class => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasResourceFactory::class,
            \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Resource::class => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1ResourceFactory::class,
        ],
    ],
    'zf-rest' => [
        'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaResource::class,
            'route_name' => 'medical-record.rest.diagnosa',
            'route_identifier_name' => 'id',
            'collection_name' => 'diagnosa',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'UTAMA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaCollection::class,
            'service_name' => 'Diagnosa',
        ],
        'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Operasi\OperasiResource::class,
            'route_name' => 'medical-record.rest.operasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'operasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'DOKTER',
                2 => 'STATUS',
                3 => 'KUNJUNGAN',
                4 => 'TANGGAL',
                5 => 'NORM',
                6 => 'NAMA_OPERASI',
                7 => 'start',
                8 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Operasi\OperasiEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Operasi\OperasiCollection::class,
            'service_name' => 'Operasi',
        ],
        'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\ICD10\ICD10Resource::class,
            'route_name' => 'medical-record.rest.icd10',
            'route_identifier_name' => 'id',
            'collection_name' => 'icd10',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'UTAMA',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\ICD10\ICD10Entity::class,
            'collection_class' => \MedicalRecord\V1\Rest\ICD10\ICD10Collection::class,
            'service_name' => 'ICD10',
        ],
        'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMResource::class,
            'route_name' => 'medical-record.rest.icd9-cm',
            'route_identifier_name' => 'id',
            'collection_name' => 'icd9_cm',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'TINDAKAN',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMCollection::class,
            'service_name' => 'ICD9CM',
        ],
        'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanResource::class,
            'route_name' => 'medical-record.rest.operasi-di-tindakan',
            'route_identifier_name' => 'id',
            'collection_name' => 'operasi_di_tindakan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'TINDAKAN_MEDIS',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanCollection::class,
            'service_name' => 'OperasiDiTindakan',
        ],
        'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianResource::class,
            'route_name' => 'medical-record.rest.icd10-kematian',
            'route_identifier_name' => 'id',
            'collection_name' => 'icd10_kematian',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'UTAMA',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianCollection::class,
            'service_name' => 'ICD10Kematian',
        ],
        'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisResource::class,
            'route_name' => 'medical-record.rest.anamnesis',
            'route_identifier_name' => 'anamnesis_id',
            'collection_name' => 'anamnesis',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'PENDAFTARAN',
                2 => 'STATUS',
                3 => 'NORM',
                4 => 'HISTORY',
                5 => 'NOT',
                6 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisCollection::class,
            'service_name' => 'Anamnesis',
        ],
        'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikResource::class,
            'route_name' => 'medical-record.rest.pemeriksaan-fisik',
            'route_identifier_name' => 'id',
            'collection_name' => 'pemeriksaan_fisik',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'PENDAFTARAN',
                2 => 'STATUS',
                3 => 'NORM',
                4 => 'HISTORY',
                5 => 'NOT',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikCollection::class,
            'service_name' => 'PemeriksaanFisik',
        ],
        'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitResource::class,
            'route_name' => 'medical-record.rest.riwayat-perjalanan-penyakit',
            'route_identifier_name' => 'riwayat_perjalanan_penyakit_id',
            'collection_name' => 'riwayat_perjalanan_penyakit',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NORM',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'start',
                6 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitCollection::class,
            'service_name' => 'RiwayatPerjalananPenyakit',
        ],
        'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiResource::class,
            'route_name' => 'medical-record.rest.riwayat-alergi',
            'route_identifier_name' => 'id',
            'collection_name' => 'riwayat_alergi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NORM',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'limit',
                6 => 'sort',
                7 => 'start',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiCollection::class,
            'service_name' => 'RiwayatAlergi',
        ],
        'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\TandaVital\TandaVitalResource::class,
            'route_name' => 'medical-record.rest.tanda-vital',
            'route_identifier_name' => 'id',
            'collection_name' => 'tanda_vital',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NOT',
                3 => 'sort',
                4 => 'HISTORY',
                5 => 'OLEH',
                6 => 'NORM',
                7 => 'limit',
                8 => 'start',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\TandaVital\TandaVitalEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\TandaVital\TandaVitalCollection::class,
            'service_name' => 'TandaVital',
        ],
        'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasResource::class,
            'route_name' => 'medical-record.rest.peminjaman-berkas',
            'route_identifier_name' => 'id',
            'collection_name' => 'peminjaman_berkas',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NORM',
                1 => 'NO_IDENTITAS',
                2 => 'STATUS',
                3 => 'TLP',
                4 => 'JENIS_KELAMIN',
                5 => 'QUERY',
                6 => 'EMAIL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasCollection::class,
            'service_name' => 'PeminjamanBerkas',
        ],
        'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Resource::class,
            'route_name' => 'medical-record.rest.peminjaman-berkas1',
            'route_identifier_name' => 'id',
            'collection_name' => 'peminjaman_berkas1',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NORM',
                1 => 'STATUS',
                2 => 'TLP',
                3 => 'EMAIL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Entity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Collection::class,
            'service_name' => 'PeminjamanBerkas1',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => 'Json',
        ],
        'accept_whitelist' => [
            'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \MedicalRecord\V1\Rest\Diagnosa\DiagnosaEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.diagnosa',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \MedicalRecord\V1\Rest\Diagnosa\DiagnosaCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.diagnosa',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\Operasi\OperasiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \MedicalRecord\V1\Rest\Operasi\OperasiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\ICD10\ICD10Entity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd10',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \MedicalRecord\V1\Rest\ICD10\ICD10Collection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd10',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\ICD9CM\ICD9CMEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd9-cm',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \MedicalRecord\V1\Rest\ICD9CM\ICD9CMCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd9-cm',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi-di-tindakan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi-di-tindakan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.icd10-kematian',
                'route_identifier_name' => 'id',
                'hydrator' => 'Zend\\Stdlib\\Hydrator\\ArraySerializable',
            ],
            \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.icd10-kematian',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\Anamnesis\AnamnesisEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.anamnesis',
                'route_identifier_name' => 'anamnesis_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \MedicalRecord\V1\Rest\Anamnesis\AnamnesisCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.anamnesis',
                'route_identifier_name' => 'anamnesis_id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.pemeriksaan-fisik',
                'route_identifier_name' => 'id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.pemeriksaan-fisik',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.riwayat-perjalanan-penyakit',
                'route_identifier_name' => 'riwayat_perjalanan_penyakit_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.riwayat-perjalanan-penyakit',
                'route_identifier_name' => 'riwayat_perjalanan_penyakit_id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.riwayat-alergi',
                'route_identifier_name' => 'id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.riwayat-alergi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\TandaVital\TandaVitalEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.tanda-vital',
                'route_identifier_name' => 'id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \MedicalRecord\V1\Rest\TandaVital\TandaVitalCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.tanda-vital',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas',
                'route_identifier_name' => 'id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Entity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas1',
                'route_identifier_name' => 'id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Collection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas1',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
        ],
    ],
];
